//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int HesapId { get; set; }
        public string HesapNo { get; set; }
        public string Bakiye { get; set; }
        public int Id { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
