//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClientDBEntities : DbContext
    {
        public ClientDBEntities()
            : base("name=ClientDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Hareket> Harekets { get; set; }
        public virtual DbSet<Hesap> Hesaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int AddHesap(string hesapNo, string bakiye, Nullable<int> id)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var bakiyeParameter = bakiye != null ?
                new ObjectParameter("Bakiye", bakiye) :
                new ObjectParameter("Bakiye", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHesap", hesapNoParameter, bakiyeParameter, idParameter);
        }
    
        public virtual int BakiyeAdd(string hesapNo, string bakiye)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var bakiyeParameter = bakiye != null ?
                new ObjectParameter("Bakiye", bakiye) :
                new ObjectParameter("Bakiye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BakiyeAdd", hesapNoParameter, bakiyeParameter);
        }
    
        public virtual int BakiyeEkle(string bakiye)
        {
            var bakiyeParameter = bakiye != null ?
                new ObjectParameter("Bakiye", bakiye) :
                new ObjectParameter("Bakiye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BakiyeEkle", bakiyeParameter);
        }
    
        public virtual int DeleteHesap(string hesapNo)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteHesap", hesapNoParameter);
        }
    
        public virtual int HareketAdd(Nullable<int> id, string hesapNo, string aktarilan)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var aktarilanParameter = aktarilan != null ?
                new ObjectParameter("Aktarilan", aktarilan) :
                new ObjectParameter("Aktarilan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HareketAdd", idParameter, hesapNoParameter, aktarilanParameter);
        }
    
        public virtual int HareketE(string hesapNo, string aktarilan, string miktar)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var aktarilanParameter = aktarilan != null ?
                new ObjectParameter("Aktarilan", aktarilan) :
                new ObjectParameter("Aktarilan", typeof(string));
    
            var miktarParameter = miktar != null ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HareketE", hesapNoParameter, aktarilanParameter, miktarParameter);
        }
    
        public virtual int HareketEkle(string hesapNo, string aktarilan)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var aktarilanParameter = aktarilan != null ?
                new ObjectParameter("Aktarilan", aktarilan) :
                new ObjectParameter("Aktarilan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HareketEkle", hesapNoParameter, aktarilanParameter);
        }
    
        public virtual int HareketEkleProc(string hesapNo, string aktarilan, string miktar, string ilk, string son)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var aktarilanParameter = aktarilan != null ?
                new ObjectParameter("Aktarilan", aktarilan) :
                new ObjectParameter("Aktarilan", typeof(string));
    
            var miktarParameter = miktar != null ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(string));
    
            var ilkParameter = ilk != null ?
                new ObjectParameter("Ilk", ilk) :
                new ObjectParameter("Ilk", typeof(string));
    
            var sonParameter = son != null ?
                new ObjectParameter("Son", son) :
                new ObjectParameter("Son", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HareketEkleProc", hesapNoParameter, aktarilanParameter, miktarParameter, ilkParameter, sonParameter);
        }
    
        public virtual int HareketProc(string hesapNo, string aktarilan, string miktar, string ilk, string son, string userId)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var aktarilanParameter = aktarilan != null ?
                new ObjectParameter("Aktarilan", aktarilan) :
                new ObjectParameter("Aktarilan", typeof(string));
    
            var miktarParameter = miktar != null ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(string));
    
            var ilkParameter = ilk != null ?
                new ObjectParameter("Ilk", ilk) :
                new ObjectParameter("Ilk", typeof(string));
    
            var sonParameter = son != null ?
                new ObjectParameter("Son", son) :
                new ObjectParameter("Son", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HareketProc", hesapNoParameter, aktarilanParameter, miktarParameter, ilkParameter, sonParameter, userIdParameter);
        }
    
        public virtual int HesapE(string hesapNo, string bakiye)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var bakiyeParameter = bakiye != null ?
                new ObjectParameter("Bakiye", bakiye) :
                new ObjectParameter("Bakiye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HesapE", hesapNoParameter, bakiyeParameter);
        }
    
        public virtual int HesapEkleme(string hesapNo, string bakiye, Nullable<int> id)
        {
            var hesapNoParameter = hesapNo != null ?
                new ObjectParameter("HesapNo", hesapNo) :
                new ObjectParameter("HesapNo", typeof(string));
    
            var bakiyeParameter = bakiye != null ?
                new ObjectParameter("Bakiye", bakiye) :
                new ObjectParameter("Bakiye", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HesapEkleme", hesapNoParameter, bakiyeParameter, idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UserAdd(string name, string lastname, string password, string username)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserAdd", nameParameter, lastnameParameter, passwordParameter, usernameParameter);
        }
    }
}
