//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareket
    {
        public int Id { get; set; }
        public string HesapNo { get; set; }
        public string Aktarilan { get; set; }
        public string Miktar { get; set; }
        public string Ilk { get; set; }
        public string Son { get; set; }
        public int UserId { get; set; }
    }
}
